[hackathon] Change the size of both component-id and token with 16 bytes
ietf-teep/teep-protocol pull request #124
Opened 2021-03-04 04:43 UTC by mcd500

Unifying the size with 16 bytes of both component-id (was 15 bytes) and token (8 bytes).
It is for making the example section more realistic.

2021-03-07 00:43 UTC, dthaler requested changes

2021-03-07 00:43 UTC, dthaler commented on draft-ietf-teep-protocol.md
> +    4F                   # bytes(8) (8..64)
```suggestion
    4F                   # bytes(16) (8..64)
```

2021-03-07 00:43 UTC, dthaler commented on draft-ietf-teep-protocol.md
>          4F               # bytes(15)
```suggestion
        4F               # bytes(16)
```

2021-03-07 00:43 UTC, dthaler commented on draft-ietf-teep-protocol.md
>          4F               # bytes(15)
```suggestion
        4F               # bytes(16)
```

2021-03-07 00:43 UTC, dthaler commented on draft-ietf-teep-protocol.md
> +    4F                   # bytes(8) (8..64)
```suggestion
    4F                   # bytes(16) (8..64)
```

2021-03-08 00:45 UTC, mcd500 commented
Thanks for the detail review, I have made the changes correctly.
@dthaler please review

2021-03-08 02:01 UTC, dthaler approved these changes

2021-03-08 02:01 UTC, merged