Adding missing references
ietf-teep/teep-protocol pull request #315
Opened 2023-03-09 04:04 UTC by mcd500

2023-03-09 18:36 UTC, dthaler requested changes

2023-03-09 18:36 UTC, dthaler commented on draft-ietf-teep-protocol.md
> +  I-D.lundblade-rats-eat-media-type:
This line duplicates line 97.  But the correct reference is I-D.ietf-rats-eat-media-type.

2023-03-09 18:36 UTC, dthaler commented on draft-ietf-teep-protocol.md
> +  I-D.wallace-rats-concise-ta-stores:
Wrong reference, this was obsoleted by line 98.  Change anything that uses this to use that one.

2023-03-09 18:58 UTC, dthaler commented
I've now incorporated (I think) the correct fix into PR #313.

2023-03-10 08:01 UTC, mcd500 commented
> I've now incorporated (I think) the correct fix into PR #313.

Close this PR, move to #313.

2023-03-10 08:01 UTC, closed without merging